const appointmentEmailTemplate = (appointment) => {
  const {
    fullName,
    email,
    phone,
    age,
    appointmentDate,
    service,
    symptoms,
    status,
  } = appointment;

  return `
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>New Appointment Request</title>
</head>

<body style="margin:0;padding:0;background:#f4f7f9;font-family:Arial,Helvetica,sans-serif;">

<table width="100%" cellpadding="0" cellspacing="0" style="padding:40px 0;background:#f4f7f9;">
<tr>
<td align="center">

<table width="650" cellpadding="0" cellspacing="0" style="background:#ffffff;border-radius:12px;overflow:hidden;border:1px solid #e5e7eb;">

<tr>
<td style="background:#0f766e;padding:24px;text-align:center;color:#ffffff;">
<h1 style="margin:0;font-size:28px;">Odisha Polyclinic</h1>
<p style="margin:8px 0 0;font-size:16px;">
New Appointment Request
</p>
</td>
</tr>

<tr>
<td style="padding:32px;">

<p style="margin-top:0;font-size:16px;color:#374151;">
A new appointment has been submitted through the website.
</p>

<table width="100%" cellpadding="12" cellspacing="0" style="border-collapse:collapse;">

<tr>
<td style="background:#f8fafc;font-weight:bold;width:220px;">Patient Name</td>
<td>${fullName}</td>
</tr>

<tr>
<td style="background:#f8fafc;font-weight:bold;">Email</td>
<td>${email}</td>
</tr>

<tr>
<td style="background:#f8fafc;font-weight:bold;">Phone</td>
<td>${phone}</td>
</tr>

<tr>
<td style="background:#f8fafc;font-weight:bold;">Age</td>
<td>${age}</td>
</tr>

<tr>
<td style="background:#f8fafc;font-weight:bold;">Service</td>
<td>${service}</td>
</tr>

<tr>
<td style="background:#f8fafc;font-weight:bold;">Appointment Date</td>
<td>${new Date(appointmentDate).toLocaleDateString()}</td>
</tr>

<tr>
<td style="background:#f8fafc;font-weight:bold;">Symptoms</td>
<td>${symptoms || "Not provided"}</td>
</tr>

<tr>
<td style="background:#f8fafc;font-weight:bold;">Status</td>
<td>${status}</td>
</tr>

</table>

</td>
</tr>

<tr>
<td style="padding:20px;text-align:center;background:#f8fafc;color:#6b7280;font-size:13px;">
This email was automatically generated by the Odisha Polyclinic Appointment System.
</td>
</tr>

</table>

</td>
</tr>
</table>

</body>
</html>
`;
};

module.exports = appointmentEmailTemplate;